name: CI/CD Deploy

on:
  push:
    branches: ["master"]

permissions:
  contents: read

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    env:
      POST_DEPLOY_CMD: ${{ secrets.POST_DEPLOY_CMD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Prepare SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
        run: |
          set -e
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          if [ -z "$SSH_PORT" ]; then SSH_PORT=22; fi
          ssh-keyscan -p "$SSH_PORT" "$SSH_HOST" >> ~/.ssh/known_hosts

      - name: Deploy dist/ to server via rsync over SSH
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
          set -e
          if [ -z "$SSH_PORT" ]; then SSH_PORT=22; fi
          rsync -az --delete -e "ssh -p $SSH_PORT" dist/ "$SSH_USER@$SSH_HOST:$DEPLOY_PATH"

      - name: Post-deploy command (optional)
        if: ${{ env.POST_DEPLOY_CMD != '' }}
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          POST_DEPLOY_CMD: ${{ env.POST_DEPLOY_CMD }}
        run: |
          set -e
          if [ -z "$SSH_PORT" ]; then SSH_PORT=22; fi
          ssh -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" "$POST_DEPLOY_CMD"


